# Generated by Django 4.2 on 2023-07-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.PositiveIntegerField()),
                ('loan_type', models.CharField(choices=[('loan_provider', 'Loan Provider'), ('loan_customer', 'Loan Customer')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='loan_provider',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='loan_term',
        ),
        migrations.RemoveField(
            model_name='loanprovider',
            name='total_budget',
        ),
        migrations.CreateModel(
            name='LoanFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loanplan')),
                ('loan_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loanprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loancustomer')),
                ('loan_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_management.loanplan')),
            ],
        ),
    ]
