# Generated by Django 4.2 on 2023-07-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0003_alter_loan_loan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanfund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
