# Generated by Django 4.2 on 2023-07-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0004_loanfund_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanfund',
            old_name='updated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='loanfund',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
