# Generated by Django 4.2 on 2023-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0005_rename_updated_at_loanfund_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
