# Generated by Django 4.2 on 2023-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0006_alter_loanfund_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanfund',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
