# Generated by Django 4.2 on 2023-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0007_alter_loanfund_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
