# Generated by Django 4.2 on 2023-07-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0008_loan_created_at_loan_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total_amount',
            new_name='amount',
        ),
    ]
