# Generated by Django 4.2 on 2023-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management', '0009_rename_total_amount_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_with_interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanfund',
            name='amount_with_interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
